version: "3.7"
services:
  mysqldb:
    #was: image: "mysql:8.0"
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - zuerich
    environment:
      MYSQL_DATABASE: items
      MYSQL_USER: itemmanagerusr
      MYSQL_PASSWORD: itemmanagerusrpsw
      MYSQL_ROOT_PASSWORD: itemmanagerusrpsw
    volumes:
      - db_datavolume:/var/lib/mysql
  api_service:
    #build: .
    image: "eliopetrini/itemmanager"
    restart: always
    ports:
      - 8080:8080
    networks:
      - zuerich
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/items?allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "itemmanagerusr",
        "spring.datasource.password" : "itemmanagerusrpsw",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"
      }'
    depends_on:
      - mysqldb
    volumes:
      - db_datavolume:/var/lib/mysql
networks:
  zuerich:
volumes:
  db_datavolume: